//! Encryption and crypto control-plane primitives for qdrant-sec.
//!
//! This crate intentionally keeps cryptographic boundaries outside the hot vector
//! storage path until the OpenFHE backend is configured. The types here are
//! serializable and testable without linking OpenFHE into every Qdrant build.

pub mod aead;
pub mod control_plane;
pub mod openfhe;
pub mod payload;
pub mod private_hnsw_client;
pub mod private_hnsw_oram;
pub mod private_result_oram;
pub mod vector;

pub use aead::{
    AeadCipher, AeadKeyring, CKKS_VECTOR_KEY_DOMAIN, EncryptedEnvelope, EncryptionContext,
    EncryptionError, EncryptionPurpose, LOCAL_RESOURCE_KEY_WRAP_CIPHERTEXT_B64_LEN,
    LOCAL_RESOURCE_KEY_WRAP_CIPHERTEXT_LEN, LocalMasterKeyProvider, METADATA_VALUE_KEY_DOMAIN,
    MasterKeyProvider, PAYLOAD_TEXT_KEY_DOMAIN, RESOURCE_KEY_WRAP_ALGORITHM, SecretKey,
    WrappedKeyBlob, rewrap_resource_key,
};
pub use control_plane::{
    CLIENT_PAYLOAD_ENVELOPE_BINDING, CiphertextEnvelope, CompiledCollectionCryptoPlan,
    CompiledMetadataRule, CompiledPayloadRule, CompiledVectorRule, ControlPlaneError,
    CryptoCapability, CryptoRegistry, CryptoSuite, GENERIC_CIPHERTEXT_MARKER,
    METADATA_AES_GCM_PROVIDER, METADATA_BLIND_INDEX_PROVIDER, METADATA_EXACT_MATCH_TOKEN_BINDING,
    METADATA_VALUE_BINDING, MetadataProviderFactory, PAYLOAD_AES_GCM_PROVIDER,
    PAYLOAD_CLIENT_AEAD_PROVIDER, PAYLOAD_FIELD_BINDING, PAYLOAD_PRIVATE_RESULT_ORAM_PROVIDER,
    PRIVATE_HNSW_ORAM_BINDING, PRIVATE_RESULT_ORAM_BINDING, PayloadProviderFactory,
    VECTOR_CLIENT_CKKS_PROVIDER, VECTOR_ENVELOPE_BINDING, VECTOR_OPENFHE_CKKS_PROVIDER,
    VECTOR_PRIVATE_HNSW_ORAM_PROVIDER, VectorProviderFactory,
};
pub use openfhe::CommandOpenFheBackend;
pub use payload::{
    CLIENT_ENCRYPTED_PAYLOAD_MARKER, ClientPayloadEnvelopeKey, ClientPayloadNonceReplayKey,
    ClientPayloadSignatureVerification, ClientPayloadValidationContext,
    ClientPayloadVerifiedEnvelopeKey, ENCRYPTED_PAYLOAD_MARKER, ExistingPayloadMode,
    METADATA_VALUE_ENVELOPE_KIND, PAYLOAD_TEXT_ENVELOPE_KIND, PayloadEncryptionError,
    PayloadEncryptionPolicy, PayloadTextEncryptor, ServerPayloadEnvelopeKey,
    ServerPayloadValidationContext, ServerPayloadVerifiedEnvelopeKey, client_payload_envelope_key,
    client_payload_nonce_replay_key, client_payload_signature_key_id,
    client_payload_signature_message, is_client_encrypted_payload_value,
    is_encrypted_payload_value, server_payload_envelope_key, validate_client_payload_value,
    validate_client_payload_value_after_runtime_verification,
    validate_client_payload_value_for_runtime,
    validate_server_payload_value_after_runtime_encryption,
    validate_server_payload_value_for_peer_replay, validate_server_payload_value_metadata,
};
pub use private_hnsw_client::{
    PRIVATE_HNSW_BLIND_RESULT_DOMAIN, PRIVATE_HNSW_BUCKET_AEAD_DOMAIN,
    PRIVATE_HNSW_NODE_AEAD_DOMAIN, PRIVATE_HNSW_ORAM_MERKLE_PROOF_KIND,
    PRIVATE_HNSW_PAYLOAD_TOKEN_DOMAIN, PRIVATE_HNSW_POSITION_MAP_DOMAIN,
    PrivateHnswBucketAeadBaseContext, PrivateHnswBucketAeadContext, PrivateHnswBuildPoint,
    PrivateHnswClientCommitBucketRef, PrivateHnswClientCommitPlan, PrivateHnswClientError,
    PrivateHnswClientKeys, PrivateHnswClientNodeCache, PrivateHnswClientStateAeadContext,
    PrivateHnswCommitSignatureContext, PrivateHnswDirectionalNeighborFilterPlan,
    PrivateHnswEncryptedClientStateSnapshot, PrivateHnswEncryptedIndexBuild,
    PrivateHnswEncryptedPathBatch, PrivateHnswGraphTraversalPathBatchPlan,
    PrivateHnswManifestBuildContext, PrivateHnswMerkleSiblingPosition,
    PrivateHnswNodeBlockPlaintext, PrivateHnswOramAccessResult, PrivateHnswOramClientConfig,
    PrivateHnswOramClientState, PrivateHnswOramClientStateSnapshot, PrivateHnswOramMerkleProof,
    PrivateHnswOramMerkleProofLeaf, PrivateHnswOramMerkleSibling, PrivateHnswOramPlaintextBucket,
    PrivateHnswOramUploadBundle, PrivateHnswPlaintextIndexBuild,
    PrivateHnswPositionMapSnapshotEntry, PrivateHnswPrivateResultFetchPlan,
    PrivateHnswPrivateResultPayload, PrivateHnswPrivateResultPayloadFetch,
    PrivateHnswSearchAccessMetrics, PrivateHnswSearchHit, PrivateHnswSearchParams,
    PrivateHnswSearchResult, PrivateHnswSpeculativePrefetchPlan, PrivateHnswVectorEncoding,
    access_private_hnsw_oram_path, build_private_hnsw_oram_manifest_from_encrypted_index,
    build_private_hnsw_oram_plaintext_index_from_auto_layered_f32_points,
    build_private_hnsw_oram_plaintext_index_from_blocks,
    build_private_hnsw_oram_plaintext_index_from_f32_points,
    build_private_hnsw_oram_plaintext_index_from_layered_f32_points,
    decode_private_hnsw_node_block, decode_private_hnsw_oram_bucket_plaintext,
    decode_private_hnsw_oram_leaf_label, empty_private_hnsw_oram_plaintext_bucket,
    encode_private_hnsw_node_block, encode_private_hnsw_oram_bucket_plaintext,
    encode_private_hnsw_oram_leaf_label, finalize_private_hnsw_private_result_fetch,
    open_private_hnsw_oram_bucket, open_private_hnsw_oram_client_state_snapshot,
    open_private_hnsw_oram_plaintext_bucket, open_private_hnsw_oram_verified_path_batch,
    package_private_hnsw_oram_upload_bundle, plan_private_hnsw_oram_commit,
    plan_private_hnsw_oram_commit_for_manifest, plan_private_hnsw_oram_directional_neighbor_filter,
    plan_private_hnsw_oram_graph_traversal_path_batch,
    plan_private_hnsw_oram_graph_traversal_path_batch_with_stats,
    plan_private_hnsw_oram_neighbor_clustered_leaves, plan_private_hnsw_oram_speculative_prefetch,
    plan_private_hnsw_private_result_fetch_tokens, private_hnsw_bucket_commitment,
    private_hnsw_level_from_node_id, private_hnsw_node_reaches_level,
    private_hnsw_oram_bucket_count, private_hnsw_oram_bucket_ids_for_leaf,
    private_hnsw_oram_bucket_ids_for_leaf_labels, private_hnsw_oram_fixed_writeback_bucket_budget,
    private_hnsw_oram_leaf_count, private_hnsw_oram_merkle_root_for_commitments,
    refresh_private_hnsw_oram_manifest_for_commit, seal_private_hnsw_oram_bucket,
    seal_private_hnsw_oram_client_state_snapshot, seal_private_hnsw_oram_plaintext_bucket,
    seal_private_hnsw_oram_plaintext_index, search_private_hnsw_oram_encrypted,
    search_private_hnsw_oram_encrypted_verified,
    search_private_hnsw_oram_encrypted_verified_with_cache,
    search_private_hnsw_oram_encrypted_with_cache, search_private_hnsw_oram_plaintext,
    search_private_hnsw_oram_plaintext_with_cache, sign_private_hnsw_oram_commit,
    sign_private_hnsw_oram_manifest, sign_private_hnsw_oram_manifest_refresh,
    sign_private_hnsw_oram_read_paths, sign_private_hnsw_oram_read_paths_for_manifest,
    validate_private_hnsw_oram_upload_bundle,
    validate_private_hnsw_oram_upload_bundle_with_signature,
    validate_private_hnsw_search_fixed_budget, validate_private_hnsw_search_result_privacy,
    validate_private_hnsw_strict_search_result, verify_private_hnsw_oram_merkle_proof,
    verify_private_hnsw_oram_merkle_proof_json,
};
pub use private_hnsw_oram::{
    DistanceKind, FixedBudgetParams, OramKind, OramParams,
    PRIVATE_HNSW_ORAM_COMMIT_SIGNATURE_DOMAIN, PRIVATE_HNSW_ORAM_MANIFEST_SIGNATURE_DOMAIN,
    PRIVATE_HNSW_ORAM_READ_PATHS_SIGNATURE_DOMAIN, PrivateHnswEpoch,
    PrivateHnswManifestValidationContext, PrivateHnswOramBucket, PrivateHnswOramCommitBucketRef,
    PrivateHnswOramCommitSignatureInput, PrivateHnswOramError, PrivateHnswOramManifest,
    PrivateHnswOramReadPathsSignatureInput, PrivateHnswOramSignature, PrivateHnswParams,
    PrivateHnswSignatureVerification, ResultPrivacyMode, private_hnsw_min_f32_node_block_bytes,
    private_hnsw_oram_bucket_ciphertext_bytes, private_hnsw_oram_commit_signature_message,
    private_hnsw_oram_manifest_signature_message, private_hnsw_oram_read_paths_signature_message,
    validate_private_hnsw_oram_commit_signature, validate_private_hnsw_oram_manifest,
    validate_private_hnsw_oram_manifest_shape, validate_private_hnsw_oram_manifest_signature,
    validate_private_hnsw_oram_manifest_signature_shape,
    validate_private_hnsw_oram_read_paths_signature,
};
pub use private_result_oram::{
    PRIVATE_RESULT_ORAM_BUCKET_AEAD_DOMAIN, PRIVATE_RESULT_ORAM_BUCKET_COMMITMENT_DOMAIN,
    PRIVATE_RESULT_ORAM_CLIENT_STATE_AEAD_DOMAIN, PRIVATE_RESULT_ORAM_COMMIT_SIGNATURE_DOMAIN,
    PRIVATE_RESULT_ORAM_MANIFEST_SIGNATURE_DOMAIN, PRIVATE_RESULT_ORAM_MERKLE_PROOF_KIND,
    PRIVATE_RESULT_ORAM_READ_BUCKETS_SIGNATURE_DOMAIN, PrivateResultOramAccessResult,
    PrivateResultOramBucket, PrivateResultOramBucketAeadBaseContext,
    PrivateResultOramBucketAeadContext, PrivateResultOramBucketCommitmentContext,
    PrivateResultOramBucketValidationContext, PrivateResultOramClientCommitBucketRef,
    PrivateResultOramClientConfig, PrivateResultOramClientKeys, PrivateResultOramClientState,
    PrivateResultOramClientStateAeadContext, PrivateResultOramClientStateSnapshot,
    PrivateResultOramCommitBucketRef, PrivateResultOramCommitPlan,
    PrivateResultOramCommitSignatureContext, PrivateResultOramCommitSignatureInput,
    PrivateResultOramEncryptedBucketBatch, PrivateResultOramEncryptedClientStateSnapshot,
    PrivateResultOramEpoch, PrivateResultOramError, PrivateResultOramFetchTokenPosition,
    PrivateResultOramManifest, PrivateResultOramManifestValidationContext,
    PrivateResultOramMerkleProof, PrivateResultOramMerkleProofLeaf, PrivateResultOramMerkleSibling,
    PrivateResultOramMerkleSiblingPosition, PrivateResultOramPayloadBlockPlaintext,
    PrivateResultOramPlaintextBucket, PrivateResultOramPositionMapSnapshotEntry,
    PrivateResultOramReadBucketBatchPlan, PrivateResultOramReadBucketPlan,
    PrivateResultOramReadBucketsSignatureContext, PrivateResultOramReadBucketsSignatureInput,
    PrivateResultOramSignature, PrivateResultOramSignatureVerification,
    PrivateResultOramTokenFetchAccess, PrivateResultOramTokenFetchResult,
    PrivateResultOramUploadBundle, access_private_result_oram_path,
    decode_private_result_oram_bucket_plaintext, decode_private_result_oram_leaf_label,
    decode_private_result_oram_payload_block, empty_private_result_oram_plaintext_bucket,
    encode_private_result_oram_bucket_plaintext, encode_private_result_oram_leaf_label,
    encode_private_result_oram_payload_block, fetch_private_result_oram_tokens_encrypted_verified,
    open_private_result_oram_bucket, open_private_result_oram_client_state_snapshot,
    open_private_result_oram_plaintext_bucket, open_private_result_oram_verified_bucket_batch,
    package_private_result_oram_upload_bundle, plan_private_result_oram_commit,
    plan_private_result_oram_commit_for_manifest,
    plan_private_result_oram_read_bucket_batches_for_fetch_tokens,
    private_result_oram_bucket_ciphertext_bytes, private_result_oram_bucket_commitment,
    private_result_oram_bucket_count, private_result_oram_bucket_ids_for_leaf,
    private_result_oram_client_config_from_manifest, private_result_oram_commit_signature_message,
    private_result_oram_fixed_writeback_bucket_budget, private_result_oram_leaf_count,
    private_result_oram_manifest_signature_message,
    private_result_oram_merkle_root_for_commitments,
    private_result_oram_read_buckets_signature_message,
    refresh_private_result_oram_manifest_for_commit, seal_private_result_oram_bucket,
    seal_private_result_oram_client_state_snapshot, seal_private_result_oram_plaintext_bucket,
    sign_private_result_oram_commit, sign_private_result_oram_manifest,
    sign_private_result_oram_manifest_refresh, sign_private_result_oram_read_buckets,
    sign_private_result_oram_read_buckets_for_manifest, validate_private_result_oram_bucket_shape,
    validate_private_result_oram_client_config, validate_private_result_oram_commit_signature,
    validate_private_result_oram_manifest, validate_private_result_oram_manifest_shape,
    validate_private_result_oram_manifest_signature,
    validate_private_result_oram_manifest_signature_shape,
    validate_private_result_oram_read_buckets_signature,
    validate_private_result_oram_upload_bundle,
    validate_private_result_oram_upload_bundle_with_signature,
    verify_private_result_oram_merkle_proof, verify_private_result_oram_merkle_proof_json,
};
pub use vector::{
    CKKS_PROFILE_OPENFHE_128_N16384_D4_SCALE50, CKKS_PUBLIC_MATERIAL_MAX_CRYPTO_CONTEXT_BYTES,
    CKKS_PUBLIC_MATERIAL_MAX_PUBLIC_KEY_BYTES, CKKS_SCHEME, CLIENT_CKKS_VECTOR_MARKER,
    CkksBatchEncryptionInput, CkksEncryptedQueryScoreBatchInput, CkksEncryptedQueryScoreBatchItem,
    CkksEncryptedQueryScoreInput, CkksEncryptionInput, CkksError, CkksParameters,
    CkksPlaintextQueryScoreBatchInput, CkksPlaintextQueryScoreInput, CkksPublicMaterial,
    CkksQueryEncryptionInput, CkksVectorBackend, CkksVectorBatchItem, CkksVectorEncryptor,
    CkksVectorSidecarDeleteTarget, CkksVectorSidecarEnvelopeKey,
    CkksVectorVerifiedSidecarDeleteKey, CkksVectorVerifiedSidecarKey,
    ClientCkksVectorSidecarEnvelopeKey, ClientCkksVectorSignatureVerification,
    ClientCkksVectorValidationContext, ClientCkksVectorVerifiedSidecarKey,
    ENCRYPTED_CKKS_VECTOR_MARKER, ENCRYPTED_VECTOR_SIDECAR_FIELD, EncryptedCkksVector,
    VerifiedCkksVector, ckks_vector_sidecar_envelope_key, ckks_vector_verified_sidecar_delete_key,
    client_ckks_vector_sidecar_envelope_key, client_ckks_vector_signature_message,
    encrypted_ckks_vector_payload_value, is_client_ckks_vector_payload_value,
    is_encrypted_ckks_vector_payload_value, validate_client_ckks_vector_payload_value_for_runtime,
};
