//! Encryption and crypto control-plane primitives for qdrant-sec.
//!
//! This crate intentionally keeps cryptographic boundaries outside the hot vector
//! storage path until the OpenFHE backend is configured. The types here are
//! serializable and testable without linking OpenFHE into every Qdrant build.

pub mod aead;
pub mod control_plane;
pub mod openfhe;
pub mod payload;
pub mod private_hnsw_client;
pub mod private_hnsw_oram;
pub mod private_oram_activation_authority;
pub mod private_oram_append_checkpoint;
pub mod private_oram_append_client;
pub mod private_oram_append_finalizer;
pub mod private_oram_append_owner_prepare;
pub mod private_oram_append_result_transaction;
pub mod private_oram_append_transaction;
pub mod private_oram_mutation;
pub mod private_oram_peer_activation;
pub mod private_oram_peer_recovery;
pub mod private_oram_point_staging;
pub mod private_oram_recovery;
pub mod private_result_oram;
pub mod vector;

pub use aead::{
    AeadCipher, AeadKeyring, CKKS_VECTOR_KEY_DOMAIN, EncryptedEnvelope, EncryptionContext,
    EncryptionError, EncryptionPurpose, LOCAL_RESOURCE_KEY_WRAP_CIPHERTEXT_B64_LEN,
    LOCAL_RESOURCE_KEY_WRAP_CIPHERTEXT_LEN, LocalMasterKeyProvider, METADATA_VALUE_KEY_DOMAIN,
    MasterKeyProvider, PAYLOAD_TEXT_KEY_DOMAIN, RESOURCE_KEY_WRAP_ALGORITHM, SecretKey,
    WrappedKeyBlob, rewrap_resource_key,
};
pub use control_plane::{
    CLIENT_PAYLOAD_ENVELOPE_BINDING, CiphertextEnvelope, CompiledCollectionCryptoPlan,
    CompiledMetadataRule, CompiledPayloadRule, CompiledVectorRule, ControlPlaneError,
    CryptoCapability, CryptoRegistry, CryptoSuite, GENERIC_CIPHERTEXT_MARKER,
    METADATA_AES_GCM_PROVIDER, METADATA_BLIND_INDEX_PROVIDER, METADATA_EXACT_MATCH_TOKEN_BINDING,
    METADATA_VALUE_BINDING, MetadataProviderFactory, PAYLOAD_AES_GCM_PROVIDER,
    PAYLOAD_CLIENT_AEAD_PROVIDER, PAYLOAD_FIELD_BINDING, PAYLOAD_PRIVATE_RESULT_ORAM_PROVIDER,
    PRIVATE_HNSW_ORAM_BINDING, PRIVATE_RESULT_ORAM_BINDING, PayloadProviderFactory,
    VECTOR_CLIENT_CKKS_PROVIDER, VECTOR_ENVELOPE_BINDING, VECTOR_OPENFHE_CKKS_PROVIDER,
    VECTOR_PRIVATE_HNSW_ORAM_PROVIDER, VectorProviderFactory,
};
pub use openfhe::CommandOpenFheBackend;
pub use payload::{
    CLIENT_ENCRYPTED_PAYLOAD_MARKER, ClientPayloadEnvelopeKey, ClientPayloadNonceReplayKey,
    ClientPayloadSignatureVerification, ClientPayloadValidationContext,
    ClientPayloadVerifiedEnvelopeKey, ENCRYPTED_PAYLOAD_MARKER, ExistingPayloadMode,
    METADATA_VALUE_ENVELOPE_KIND, PAYLOAD_TEXT_ENVELOPE_KIND, PayloadEncryptionError,
    PayloadEncryptionPolicy, PayloadTextEncryptor, ServerPayloadEnvelopeKey,
    ServerPayloadValidationContext, ServerPayloadVerifiedEnvelopeKey, client_payload_envelope_key,
    client_payload_nonce_replay_key, client_payload_signature_key_id,
    client_payload_signature_message, is_client_encrypted_payload_value,
    is_encrypted_payload_value, server_payload_envelope_key, validate_client_payload_value,
    validate_client_payload_value_after_runtime_verification,
    validate_client_payload_value_for_runtime,
    validate_server_payload_value_after_runtime_encryption,
    validate_server_payload_value_for_peer_replay, validate_server_payload_value_metadata,
};
pub use private_hnsw_client::{
    PRIVATE_HNSW_BLIND_RESULT_DOMAIN, PRIVATE_HNSW_BUCKET_AEAD_DOMAIN,
    PRIVATE_HNSW_NODE_AEAD_DOMAIN, PRIVATE_HNSW_NODE_BLOCK_VERSION,
    PRIVATE_HNSW_ORAM_MERKLE_PROOF_KIND, PRIVATE_HNSW_PAYLOAD_TOKEN_DOMAIN,
    PRIVATE_HNSW_POSITION_MAP_DOMAIN, PrivateHnswBucketAeadBaseContext,
    PrivateHnswBucketAeadContext, PrivateHnswBuildPoint, PrivateHnswClientCommitBucketRef,
    PrivateHnswClientCommitPlan, PrivateHnswClientError, PrivateHnswClientKeys,
    PrivateHnswClientNodeCache, PrivateHnswClientStateAeadContext,
    PrivateHnswCommitSignatureContext, PrivateHnswDirectionalNeighborFilterPlan,
    PrivateHnswEncryptedClientStateSnapshot, PrivateHnswEncryptedIndexBuild,
    PrivateHnswEncryptedPathBatch, PrivateHnswGraphTraversalPathBatchPlan,
    PrivateHnswManifestBuildContext, PrivateHnswMerkleSiblingPosition,
    PrivateHnswNodeBlockPlaintext, PrivateHnswOramAccessResult, PrivateHnswOramClientConfig,
    PrivateHnswOramClientState, PrivateHnswOramClientStateSnapshot, PrivateHnswOramEvictionResult,
    PrivateHnswOramMerkleProof, PrivateHnswOramMerkleProofLeaf, PrivateHnswOramMerkleSibling,
    PrivateHnswOramPlaintextBucket, PrivateHnswOramUploadBundle, PrivateHnswPlaintextIndexBuild,
    PrivateHnswPositionMapSnapshotEntry, PrivateHnswPrivateResultFetchPlan,
    PrivateHnswPrivateResultPayload, PrivateHnswPrivateResultPayloadFetch,
    PrivateHnswSearchAccessMetrics, PrivateHnswSearchHit, PrivateHnswSearchParams,
    PrivateHnswSearchResult, PrivateHnswSpeculativePrefetchPlan, PrivateHnswVectorEncoding,
    access_private_hnsw_oram_path, access_private_hnsw_oram_path_with_append_rewrite,
    build_private_hnsw_oram_manifest_from_encrypted_index,
    build_private_hnsw_oram_plaintext_index_from_auto_layered_f32_points,
    build_private_hnsw_oram_plaintext_index_from_blocks,
    build_private_hnsw_oram_plaintext_index_from_f32_points,
    build_private_hnsw_oram_plaintext_index_from_layered_f32_points,
    decode_private_hnsw_f32_vector, decode_private_hnsw_node_block,
    decode_private_hnsw_oram_bucket_plaintext, decode_private_hnsw_oram_leaf_label,
    empty_private_hnsw_oram_plaintext_bucket, encode_private_hnsw_node_block,
    encode_private_hnsw_oram_bucket_plaintext, encode_private_hnsw_oram_leaf_label,
    evict_private_hnsw_oram_path, finalize_private_hnsw_private_result_fetch,
    open_private_hnsw_oram_bucket, open_private_hnsw_oram_client_state_snapshot,
    open_private_hnsw_oram_plaintext_bucket, open_private_hnsw_oram_verified_path_batch,
    package_private_hnsw_oram_upload_bundle, plan_private_hnsw_oram_commit,
    plan_private_hnsw_oram_commit_for_manifest, plan_private_hnsw_oram_commit_for_manifest_context,
    plan_private_hnsw_oram_directional_neighbor_filter,
    plan_private_hnsw_oram_graph_traversal_path_batch,
    plan_private_hnsw_oram_graph_traversal_path_batch_with_stats,
    plan_private_hnsw_oram_neighbor_clustered_leaves, plan_private_hnsw_oram_speculative_prefetch,
    plan_private_hnsw_private_result_fetch_tokens, private_hnsw_bucket_commitment,
    private_hnsw_f32_distance, private_hnsw_level_from_node_id, private_hnsw_node_reaches_level,
    private_hnsw_oram_bucket_count, private_hnsw_oram_bucket_ids_for_leaf,
    private_hnsw_oram_bucket_ids_for_leaf_labels, private_hnsw_oram_fixed_writeback_bucket_budget,
    private_hnsw_oram_leaf_count, private_hnsw_oram_merkle_root_for_commitments,
    refresh_private_hnsw_oram_manifest_for_commit, seal_private_hnsw_oram_bucket,
    seal_private_hnsw_oram_client_state_snapshot, seal_private_hnsw_oram_plaintext_bucket,
    seal_private_hnsw_oram_plaintext_index, search_private_hnsw_oram_encrypted,
    search_private_hnsw_oram_encrypted_verified,
    search_private_hnsw_oram_encrypted_verified_with_cache,
    search_private_hnsw_oram_encrypted_with_cache, search_private_hnsw_oram_plaintext,
    search_private_hnsw_oram_plaintext_with_cache, sign_private_hnsw_oram_commit,
    sign_private_hnsw_oram_manifest, sign_private_hnsw_oram_manifest_refresh,
    sign_private_hnsw_oram_read_paths, sign_private_hnsw_oram_read_paths_for_manifest,
    sign_private_hnsw_oram_read_paths_for_manifest_context,
    validate_private_hnsw_oram_upload_bundle,
    validate_private_hnsw_oram_upload_bundle_with_signature,
    validate_private_hnsw_search_fixed_budget, validate_private_hnsw_search_result_privacy,
    validate_private_hnsw_strict_search_result, verify_private_hnsw_oram_merkle_proof,
    verify_private_hnsw_oram_merkle_proof_json,
};
pub use private_hnsw_oram::{
    DistanceKind, FixedBudgetParams, OramKind, OramParams,
    PRIVATE_HNSW_ORAM_BUCKET_COMMITMENT_DOMAIN, PRIVATE_HNSW_ORAM_COMMIT_SIGNATURE_DOMAIN,
    PRIVATE_HNSW_ORAM_MANIFEST_SIGNATURE_DOMAIN, PRIVATE_HNSW_ORAM_READ_PATHS_SIGNATURE_DOMAIN,
    PrivateHnswEpoch, PrivateHnswManifestValidationContext, PrivateHnswOramBucket,
    PrivateHnswOramBucketCommitmentContext as ServerPrivateHnswOramBucketCommitmentContext,
    PrivateHnswOramBucketValidationContext as ServerPrivateHnswOramBucketValidationContext,
    PrivateHnswOramClientCommitBucketRef as ServerPrivateHnswOramClientCommitBucketRef,
    PrivateHnswOramCommitBucketRef, PrivateHnswOramCommitPlan as ServerPrivateHnswOramCommitPlan,
    PrivateHnswOramCommitSignatureInput, PrivateHnswOramError, PrivateHnswOramManifest,
    PrivateHnswOramReadPathsSignatureInput, PrivateHnswOramSignature,
    PrivateHnswOramUploadBundle as ServerPrivateHnswOramUploadBundle, PrivateHnswParams,
    PrivateHnswSignatureVerification, ResultPrivacyMode,
    package_private_hnsw_oram_upload_bundle as package_server_private_hnsw_oram_upload_bundle,
    plan_private_hnsw_oram_commit as plan_server_private_hnsw_oram_commit,
    plan_private_hnsw_oram_commit_for_manifest as plan_server_private_hnsw_oram_commit_for_manifest,
    plan_private_hnsw_oram_commit_for_manifest_context as plan_server_private_hnsw_oram_commit_for_manifest_context,
    private_hnsw_min_f32_node_block_bytes, private_hnsw_oram_bucket_ciphertext_bytes,
    private_hnsw_oram_bucket_commitment as server_private_hnsw_oram_bucket_commitment,
    private_hnsw_oram_fixed_writeback_bucket_budget as server_private_hnsw_oram_fixed_writeback_bucket_budget,
    private_hnsw_oram_merkle_root_for_commitments as server_private_hnsw_oram_merkle_root_for_commitments,
    private_hnsw_oram_writeback_digest,
    refresh_private_hnsw_oram_manifest_for_commit as refresh_server_private_hnsw_oram_manifest_for_commit,
    sign_private_hnsw_oram_manifest as sign_server_private_hnsw_oram_manifest,
    sign_private_hnsw_oram_manifest_refresh as sign_server_private_hnsw_oram_manifest_refresh,
    try_private_hnsw_oram_commit_signature_message,
    try_private_hnsw_oram_manifest_signature_message,
    try_private_hnsw_oram_read_paths_signature_message,
    validate_private_hnsw_oram_commit_signature, validate_private_hnsw_oram_manifest,
    validate_private_hnsw_oram_manifest_shape, validate_private_hnsw_oram_manifest_signature,
    validate_private_hnsw_oram_manifest_signature_shape,
    validate_private_hnsw_oram_read_paths_signature,
    validate_private_hnsw_oram_upload_bundle as validate_server_private_hnsw_oram_upload_bundle,
    validate_private_hnsw_oram_upload_bundle_with_signature as validate_server_private_hnsw_oram_upload_bundle_with_signature,
};
pub use private_oram_activation_authority::{
    PRIVATE_ORAM_ACTIVATION_AUTHORITY_KEY_ID_DOMAIN,
    PRIVATE_ORAM_ACTIVATION_AUTHORITY_MANIFEST_SIGNATURE_DOMAIN,
    PRIVATE_ORAM_ACTIVATION_AUTHORITY_MANIFEST_VERSION,
    PRIVATE_ORAM_ACTIVATION_AUTHORITY_PUBLIC_KEY_VERSION,
    PRIVATE_ORAM_ACTIVATION_AUTHORITY_SIGNATURE_ALGORITHM,
    PRIVATE_ORAM_ACTIVATION_AUTHORITY_SIGNATURE_VERSION,
    PRIVATE_ORAM_ACTIVATION_CLUSTER_IDENTITY_DIGEST_DOMAIN,
    PRIVATE_ORAM_ACTIVATION_PEER_URI_DIGEST_DOMAIN, PrivateOramActivationAuthorityBundleV1,
    PrivateOramActivationAuthorityError, PrivateOramActivationAuthorityManifestV1,
    PrivateOramActivationAuthorityPublicKeyV1, PrivateOramActivationAuthoritySignatureV1,
    PrivateOramActivationAuthorityTrustAnchorV1, PrivateOramActivationPeerPinV1,
    PrivateOramActivationPeerUriSchemeV1, PrivateOramActivationRegistryExpectationV1,
    VerifiedSignedPrivateOramActivationAuthorityManifestV1,
    package_private_oram_activation_authority_manifest_v1,
    private_oram_activation_authority_key_id_v1,
    private_oram_activation_authority_manifest_digest_v1,
    private_oram_activation_authority_public_key_v1,
    private_oram_activation_signer_from_signed_manifest_for_challenge_v1,
    sign_private_oram_activation_authority_manifest_v1,
    try_private_oram_activation_authority_manifest_signature_message_v1,
    try_private_oram_activation_cluster_identity_digest_v1,
    try_private_oram_activation_peer_uri_digest_v1,
    validate_private_oram_activation_authority_bundle_v1,
    validate_private_oram_activation_authority_manifest_v1_shape,
    validate_private_oram_activation_authority_public_key_v1,
    validate_private_oram_activation_authority_signature_v1_shape,
    validate_private_oram_activation_authority_transition_v1,
};
pub use private_oram_append_checkpoint::{
    PrivateOramAppendCheckpointError, PrivateOramAppendPairedCheckpointDeltaV2,
    PrivateOramAppendPairedCheckpointResealInputV2, PrivateOramAppendPairedCheckpointResealV2,
    plan_private_oram_append_paired_checkpoint_delta_v2,
    reseal_private_oram_append_paired_checkpoint_v2,
};
pub use private_oram_append_client::{
    PRIVATE_ORAM_APPEND_CLIENT_CHECKPOINT_AEAD_DOMAIN,
    PRIVATE_ORAM_APPEND_CLIENT_CHECKPOINT_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_CLIENT_CHECKPOINT_PLAINTEXT_V3_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_CLIENT_CHECKPOINT_V2_VERSION,
    PRIVATE_ORAM_APPEND_HNSW_CLIENT_STATE_V3_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_MERKLE_PATCH_PROOF_V1_VERSION,
    PRIVATE_ORAM_APPEND_RESULT_CLIENT_STATE_V3_DIGEST_DOMAIN, PrivateOramAppendClientCheckpointV2,
    PrivateOramAppendClientError, PrivateOramAppendClientIndexCheckpointV2,
    PrivateOramAppendHnswNeighborRewriteV2, PrivateOramAppendHnswRecordV2,
    PrivateOramAppendLevel0HnswGraphDeltaV2, PrivateOramAppendLevel0PointV2,
    PrivateOramAppendMerklePatchLeafV1, PrivateOramAppendMerklePatchProofV1,
    PrivateOramAppendMerkleSiblingPositionV1, PrivateOramAppendMerkleSiblingV1,
    PrivateOramAppendPointRecordV2, PrivateOramAppendResultRecordV2,
    PrivateOramAppendSparseMerklePatchV1, PrivateOramEncryptedAppendClientCheckpointV2,
    PrivateOramSealedAppendClientCheckpointV2, apply_private_oram_append_sparse_merkle_patch_v1,
    bind_private_oram_append_client_checkpoint_v2, open_private_oram_append_client_checkpoint_v2,
    plan_private_oram_level0_hnsw_graph_delta_v2,
    private_oram_append_client_checkpoint_plaintext_v3_digest,
    private_oram_append_client_checkpoint_v2_digest,
    private_oram_append_hnsw_client_state_v3_digest,
    private_oram_append_result_client_state_v3_digest,
    seal_private_oram_append_client_checkpoint_v2,
    try_private_oram_append_client_checkpoint_plaintext_v3_digest_message,
    try_private_oram_append_client_checkpoint_v2_digest_message,
    try_private_oram_append_hnsw_client_state_v3_digest_message,
    try_private_oram_append_result_client_state_v3_digest_message,
    validate_private_oram_append_client_checkpoint_v2,
    validate_private_oram_append_client_checkpoint_v2_shape,
};
pub use private_oram_append_finalizer::{
    PrivateOramAppendFinalizerError, PrivateOramAppendPairedFinalizationContextV1,
    PrivateOramAppendPairedFinalizationInputV1, PrivateOramAppendPairedFinalizationV1,
    finalize_private_oram_append_paired_mutation_v1,
    project_private_oram_append_paired_owner_prepare_v1,
};
pub use private_oram_append_owner_prepare::{
    PRIVATE_ORAM_APPEND_OWNER_PREPARE_V1_VERSION, PrivateOramAppendOwnerBucketBatchV1,
    PrivateOramAppendOwnerIndexPrepareV1, PrivateOramAppendOwnerPrepareError,
    PrivateOramAppendOwnerPrepareV1, PrivateOramAppendOwnerPrepareValidationContextV1,
    PrivateOramServerReadEvidenceRecorderV1, PrivateOramServerReadEvidenceV1,
    PrivateOramValidatedOwnerFinalBucketsV1, PrivateOramValidatedOwnerIndexPrepareV1,
    PrivateOramValidatedOwnerPrepareV1, validate_private_oram_append_owner_prepare_v1,
};
pub use private_oram_append_result_transaction::{
    PRIVATE_ORAM_APPEND_RESULT_ATTEMPT_V3_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_RESULT_PREPARED_COMMIT_V3_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_RESULT_PREPARED_COMMIT_V4_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_RESULT_WORKING_ARTIFACT_V3_DIGEST_DOMAIN,
    PrivateOramAppendResultAttemptDigestInputV3, PrivateOramAppendResultPointV2,
    PrivateOramAppendResultPreparedCommitDigestInputV3,
    PrivateOramAppendResultPreparedCommitDigestInputV4, PrivateOramAppendResultReadRequestV2,
    PrivateOramAppendResultTransactionOutputV2, PrivateOramAppendResultTransactionPlanV2,
    PrivateOramAppendResultTransactionProgressV2, PrivateOramAppendResultTransactionV2,
    private_oram_append_result_attempt_v3_digest,
    private_oram_append_result_prepared_commit_v3_digest,
    private_oram_append_result_prepared_commit_v4_digest,
    validate_private_oram_append_result_transaction_output_v2,
};
pub use private_oram_append_transaction::{
    PRIVATE_ORAM_APPEND_HNSW_ATTEMPT_V2_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_HNSW_ATTEMPT_V3_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_HNSW_GRAPH_DELTA_V3_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_HNSW_PREPARED_COMMIT_V2_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_HNSW_PREPARED_COMMIT_V3_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_HNSW_PREPARED_COMMIT_V4_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_RECOVERY_MARKER_V2_VERSION, PRIVATE_ORAM_APPEND_RECOVERY_MARKER_V3_VERSION,
    PrivateOramAppendHnswAttemptDigestInput, PrivateOramAppendHnswAttemptDigestInputV3,
    PrivateOramAppendHnswPreparedCommitDigestInput,
    PrivateOramAppendHnswPreparedCommitDigestInputV3,
    PrivateOramAppendHnswPreparedCommitDigestInputV4, PrivateOramAppendHnswReadRequestV2,
    PrivateOramAppendHnswTransactionOutputV2, PrivateOramAppendHnswTransactionPlanV2,
    PrivateOramAppendHnswTransactionProgressV2, PrivateOramAppendHnswTransactionV2,
    PrivateOramAppendRecoveryMarkerV2, PrivateOramAppendRecoveryMarkerV3,
    PrivateOramAppendRecoveryPhaseV2, PrivateOramAppendTransactionError,
    private_oram_append_hnsw_attempt_v2_digest, private_oram_append_hnsw_attempt_v3_digest,
    private_oram_append_hnsw_graph_delta_v3_digest,
    private_oram_append_hnsw_prepared_commit_v2_digest,
    private_oram_append_hnsw_prepared_commit_v3_digest,
    private_oram_append_hnsw_prepared_commit_v4_digest,
    validate_private_oram_append_hnsw_transaction_output_v2,
};
pub use private_oram_mutation::{
    PAYLOAD_PRIVATE_RESULT_ORAM_V2_PROVIDER, PRIVATE_HNSW_ORAM_V2_BINDING,
    PRIVATE_ORAM_APPEND_MAX_INDEXES, PRIVATE_ORAM_APPEND_MAX_MUTATION_TTL_SECS,
    PRIVATE_ORAM_APPEND_MAX_TOTAL_BUCKET_REFS, PRIVATE_ORAM_APPEND_MUTATION_V1_SIGNATURE_DOMAIN,
    PRIVATE_ORAM_APPEND_MUTATION_V1_VERSION, PRIVATE_ORAM_APPEND_READ_TRANSCRIPT_V1_DIGEST_DOMAIN,
    PRIVATE_ORAM_APPEND_WRITEBACK_V1_DIGEST_DOMAIN,
    PRIVATE_ORAM_IMMUTABLE_MANIFEST_V2_SIGNATURE_DOMAIN,
    PRIVATE_ORAM_IMMUTABLE_MANIFEST_V2_VERSION,
    PRIVATE_ORAM_NO_SERVER_POINT_RECORD_V1_DIGEST_DOMAIN,
    PRIVATE_ORAM_SIGNED_STATE_V2_SIGNATURE_DOMAIN, PRIVATE_ORAM_SIGNED_STATE_V2_VERSION,
    PRIVATE_ORAM_VISIBLE_POINT_RECORD_V1_DIGEST_DOMAIN, PRIVATE_RESULT_ORAM_V2_BINDING,
    PrivateOramAppendBucketRefV1, PrivateOramAppendIndexWritebackV1,
    PrivateOramAppendMutationBundleV1, PrivateOramAppendMutationV1,
    PrivateOramAppendReadTranscriptDigestInput, PrivateOramAppendReadWindowV1,
    PrivateOramAppendValidationContext, PrivateOramAppendWritebackDigestInput,
    PrivateOramImmutableIndexParamsV2, PrivateOramImmutableIndexV2,
    PrivateOramImmutableManifestBundleV2, PrivateOramImmutableManifestV2,
    PrivateOramIndexCapacityV2, PrivateOramIndexKindV2, PrivateOramIndexStateV2,
    PrivateOramMutationError, PrivateOramObservedReadTranscriptV1, PrivateOramPointOperationKindV1,
    PrivateOramSignature, PrivateOramSignatureVerification, PrivateOramSignedStateBundleV2,
    PrivateOramSignedStateV2, PrivateOramVisiblePointRecordV1,
    VECTOR_PRIVATE_HNSW_ORAM_V2_PROVIDER, package_private_oram_append_mutation_v1,
    package_private_oram_immutable_manifest_v2, package_private_oram_signed_state_v2,
    private_oram_append_mutation_v1_digest, private_oram_append_read_transcript_v1,
    private_oram_append_writeback_v1_digest, private_oram_immutable_manifest_v2_digest,
    private_oram_no_server_point_record_v1_digest, private_oram_signed_state_v2_digest,
    private_oram_visible_point_record_v1_digest, sign_private_oram_append_mutation_v1,
    sign_private_oram_immutable_manifest_v2, sign_private_oram_signed_state_v2,
    try_private_oram_append_mutation_v1_signature_message,
    try_private_oram_append_read_transcript_v1_digest_message,
    try_private_oram_append_writeback_v1_digest_message,
    try_private_oram_immutable_manifest_v2_signature_message,
    try_private_oram_no_server_point_record_v1_digest_message,
    try_private_oram_signed_state_v2_signature_message,
    try_private_oram_visible_point_record_v1_digest_message,
    validate_private_oram_append_mutation_v1, validate_private_oram_append_mutation_v1_shape,
    validate_private_oram_append_mutation_v1_signature,
    validate_private_oram_immutable_manifest_v2_shape,
    validate_private_oram_immutable_manifest_v2_signature, validate_private_oram_signature_shape,
    validate_private_oram_signed_state_v2_shape, validate_private_oram_signed_state_v2_signature,
};
pub use private_oram_peer_activation::{
    PRIVATE_ORAM_PEER_ACTIVATION_ACK_SIGNATURE_DOMAIN, PRIVATE_ORAM_PEER_ACTIVATION_CAPABILITY,
    PRIVATE_ORAM_PEER_ACTIVATION_CONFIGURATION_DIGEST_DOMAIN,
    PRIVATE_ORAM_PEER_ACTIVATION_PROTOCOL_VERSION, PrivateOramConsensusConfigurationV1,
    PrivateOramPeerActivationAckV1, PrivateOramPeerActivationChallengeV1,
    PrivateOramPeerActivationError, PrivateOramPeerActivationObservationV1,
    PrivateOramPeerActivationSignatureV1, PrivateOramPeerActivationSignedAckV1,
    private_oram_consensus_configuration_member_ids_v1, sign_private_oram_peer_activation_ack_v1,
    try_private_oram_consensus_configuration_digest_v1,
    try_private_oram_peer_activation_ack_signature_message_v1,
    validate_private_oram_consensus_configuration_v1,
    validate_private_oram_peer_activation_ack_signature_v1,
    validate_private_oram_peer_activation_challenge_v1_shape,
    validate_private_oram_peer_activation_observation_v1_shape,
};
pub use private_oram_peer_recovery::{
    PRIVATE_ORAM_PEER_RECOVERY_KEY_ID_DOMAIN, PRIVATE_ORAM_PEER_RECOVERY_PROTOCOL_VERSION,
    PRIVATE_ORAM_PEER_RECOVERY_PUBLIC_KEY_VERSION,
    PRIVATE_ORAM_PEER_RECOVERY_RESPONSE_SIGNATURE_DOMAIN,
    PRIVATE_ORAM_PEER_RECOVERY_SIGNATURE_ALGORITHM, PRIVATE_ORAM_PEER_RECOVERY_SIGNATURE_VERSION,
    PRIVATE_ORAM_PEER_RECOVERY_TERMINAL_EVIDENCE_DIGEST_DOMAIN, PrivateOramPeerRecoveryError,
    PrivateOramPeerRecoveryPublicKeyV1, PrivateOramPeerRecoveryRequestV2,
    PrivateOramPeerRecoverySignatureV2, PrivateOramPeerRecoveryTerminalIndexV2,
    PrivateOramPeerRecoveryTerminalKindV2, PrivateOramPeerRecoveryTerminalV2,
    VerifiedPrivateOramPeerRecoveryResponseV2, private_oram_peer_recovery_key_id,
    private_oram_peer_recovery_public_key_v1, sign_private_oram_peer_recovery_response_v2,
    try_private_oram_peer_recovery_response_signature_message_v2,
    try_private_oram_peer_recovery_terminal_evidence_digest_v2,
    validate_private_oram_peer_recovery_public_key_v1,
    validate_private_oram_peer_recovery_request_v2_shape,
    validate_private_oram_peer_recovery_response_signature_v2,
    validate_private_oram_peer_recovery_signature_v2_shape,
    validate_private_oram_peer_recovery_terminal_v2,
};
pub use private_oram_point_staging::{
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_DOMAIN, PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_BYTES,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_JSON_CONTAINER_ENTRIES,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_JSON_DEPTH,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_JSON_STRING_BYTES,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_JSON_VALUES,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_MULTI_DENSE_VECTORS,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_NAMED_VECTORS,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_SHARD_KEYWORD_BYTES,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_TARGET_SHARDS,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_TOTAL_VECTOR_VALUES,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_VECTOR_DIMENSION,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_MAX_VECTOR_NAME_BYTES,
    PRIVATE_ORAM_STAGED_INSERT_FRAME_V1_VERSION, PRIVATE_ORAM_STAGED_POINT_SEMANTIC_V1_DOMAIN,
    PrivateOramStagedInsertFrameV1, PrivateOramStagedNamedVectorV1, PrivateOramStagedPointIdV1,
    PrivateOramStagedPointV1, PrivateOramStagedShardKeyV1, PrivateOramStagedVectorV1,
    PrivateOramStagingError, decode_private_oram_staged_insert_frame_v1,
    encode_private_oram_staged_insert_frame_v1, private_oram_staged_insert_frame_v1_digest,
    private_oram_staged_point_id_canonical_string, private_oram_staged_point_semantic_v1_digest,
    validate_private_oram_staged_insert_frame_v1_against_mutation,
    validate_private_oram_staged_insert_frame_v1_against_mutation_bundle,
};
pub use private_oram_recovery::{
    PRIVATE_ORAM_EXTERNAL_RECOVERY_CHECKPOINT_SIGNATURE_DOMAIN,
    PRIVATE_ORAM_EXTERNAL_RECOVERY_CHECKPOINT_VERSION, PrivateOramExternalRecoveryCheckpoint,
    PrivateOramExternalRecoveryCheckpointBundle, PrivateOramRecoveryError,
    PrivateOramRecoverySignature, PrivateOramRecoveryValidationContext,
    package_private_oram_external_recovery_checkpoint,
    sign_private_oram_external_recovery_checkpoint,
    try_private_oram_external_recovery_checkpoint_signature_message,
    validate_private_oram_external_recovery_checkpoint,
    validate_private_oram_external_recovery_checkpoint_shape,
    validate_private_oram_recovery_signature_shape,
};
pub use private_result_oram::{
    PRIVATE_RESULT_ORAM_BUCKET_AEAD_DOMAIN, PRIVATE_RESULT_ORAM_BUCKET_COMMITMENT_DOMAIN,
    PRIVATE_RESULT_ORAM_CLIENT_STATE_AEAD_DOMAIN, PRIVATE_RESULT_ORAM_COMMIT_SIGNATURE_DOMAIN,
    PRIVATE_RESULT_ORAM_MANIFEST_SIGNATURE_DOMAIN, PRIVATE_RESULT_ORAM_MERKLE_PROOF_KIND,
    PRIVATE_RESULT_ORAM_PAYLOAD_BLOCK_VERSION, PRIVATE_RESULT_ORAM_READ_BUCKETS_SIGNATURE_DOMAIN,
    PrivateResultOramAccessResult, PrivateResultOramBucket, PrivateResultOramBucketAeadBaseContext,
    PrivateResultOramBucketAeadContext, PrivateResultOramBucketCommitmentContext,
    PrivateResultOramBucketValidationContext, PrivateResultOramClientCommitBucketRef,
    PrivateResultOramClientConfig, PrivateResultOramClientKeys, PrivateResultOramClientState,
    PrivateResultOramClientStateAeadContext, PrivateResultOramClientStateSnapshot,
    PrivateResultOramCommitBucketRef, PrivateResultOramCommitPlan,
    PrivateResultOramCommitSignatureContext, PrivateResultOramCommitSignatureInput,
    PrivateResultOramEncryptedBucketBatch, PrivateResultOramEncryptedClientStateSnapshot,
    PrivateResultOramEpoch, PrivateResultOramError, PrivateResultOramEvictionResult,
    PrivateResultOramFetchTokenPosition, PrivateResultOramManifest,
    PrivateResultOramManifestValidationContext, PrivateResultOramMerkleProof,
    PrivateResultOramMerkleProofLeaf, PrivateResultOramMerkleSibling,
    PrivateResultOramMerkleSiblingPosition, PrivateResultOramOrderedReadBucketPlan,
    PrivateResultOramPayloadBlockPlaintext, PrivateResultOramPlaintextBucket,
    PrivateResultOramPositionMapSnapshotEntry, PrivateResultOramReadBucketBatchPlan,
    PrivateResultOramReadBucketPlan, PrivateResultOramReadBucketsSignatureContext,
    PrivateResultOramReadBucketsSignatureInput, PrivateResultOramSignature,
    PrivateResultOramSignatureVerification, PrivateResultOramTokenFetchAccess,
    PrivateResultOramTokenFetchResult, PrivateResultOramUploadBundle,
    access_private_result_oram_path, decode_private_result_oram_bucket_plaintext,
    decode_private_result_oram_leaf_label, decode_private_result_oram_payload_block,
    empty_private_result_oram_plaintext_bucket, encode_private_result_oram_bucket_plaintext,
    encode_private_result_oram_leaf_label, encode_private_result_oram_payload_block,
    evict_private_result_oram_path, fetch_private_result_oram_tokens_encrypted_verified,
    open_private_result_oram_bucket, open_private_result_oram_client_state_snapshot,
    open_private_result_oram_plaintext_bucket, open_private_result_oram_verified_bucket_batch,
    package_private_result_oram_upload_bundle, plan_private_result_oram_commit,
    plan_private_result_oram_commit_for_manifest,
    plan_private_result_oram_commit_for_manifest_context,
    plan_private_result_oram_ordered_read_bucket_batches_for_fetch_tokens,
    plan_private_result_oram_read_bucket_batches_for_fetch_tokens,
    private_result_oram_bucket_ciphertext_bytes, private_result_oram_bucket_commitment,
    private_result_oram_bucket_count, private_result_oram_bucket_ids_for_leaf,
    private_result_oram_client_config_from_manifest,
    private_result_oram_fixed_writeback_bucket_budget, private_result_oram_leaf_count,
    private_result_oram_merkle_root_for_commitments, private_result_oram_writeback_digest,
    refresh_private_result_oram_manifest_for_commit, seal_private_result_oram_bucket,
    seal_private_result_oram_client_state_snapshot, seal_private_result_oram_plaintext_bucket,
    sign_private_result_oram_commit, sign_private_result_oram_manifest,
    sign_private_result_oram_manifest_refresh, sign_private_result_oram_read_buckets,
    sign_private_result_oram_read_buckets_for_manifest,
    sign_private_result_oram_read_buckets_for_manifest_context,
    try_private_result_oram_commit_signature_message,
    try_private_result_oram_manifest_signature_message,
    try_private_result_oram_read_buckets_signature_message,
    validate_private_result_oram_bucket_shape, validate_private_result_oram_client_config,
    validate_private_result_oram_commit_signature, validate_private_result_oram_manifest,
    validate_private_result_oram_manifest_shape, validate_private_result_oram_manifest_signature,
    validate_private_result_oram_manifest_signature_shape,
    validate_private_result_oram_read_buckets_signature,
    validate_private_result_oram_upload_bundle,
    validate_private_result_oram_upload_bundle_with_signature,
    verify_private_result_oram_merkle_proof, verify_private_result_oram_merkle_proof_json,
};
pub use vector::{
    CKKS_PROFILE_OPENFHE_128_N16384_D4_SCALE50, CKKS_PUBLIC_MATERIAL_MAX_CRYPTO_CONTEXT_BYTES,
    CKKS_PUBLIC_MATERIAL_MAX_PUBLIC_KEY_BYTES, CKKS_SCHEME, CLIENT_CKKS_VECTOR_MARKER,
    CkksBatchEncryptionInput, CkksEncryptedQueryScoreBatchInput, CkksEncryptedQueryScoreBatchItem,
    CkksEncryptedQueryScoreInput, CkksEncryptionInput, CkksError, CkksParameters,
    CkksPlaintextQueryScoreBatchInput, CkksPlaintextQueryScoreInput, CkksPublicMaterial,
    CkksQueryEncryptionInput, CkksVectorBackend, CkksVectorBatchItem, CkksVectorEncryptor,
    CkksVectorSidecarDeleteTarget, CkksVectorSidecarEnvelopeKey,
    CkksVectorVerifiedSidecarDeleteKey, CkksVectorVerifiedSidecarKey,
    ClientCkksVectorSidecarEnvelopeKey, ClientCkksVectorSignatureVerification,
    ClientCkksVectorValidationContext, ClientCkksVectorVerifiedSidecarKey,
    ENCRYPTED_CKKS_VECTOR_MARKER, ENCRYPTED_VECTOR_SIDECAR_FIELD, EncryptedCkksVector,
    VerifiedCkksVector, ckks_vector_sidecar_envelope_key, ckks_vector_verified_sidecar_delete_key,
    client_ckks_vector_sidecar_envelope_key, client_ckks_vector_signature_message,
    encrypted_ckks_vector_payload_value, is_client_ckks_vector_payload_value,
    is_encrypted_ckks_vector_payload_value, validate_client_ckks_vector_payload_value_for_runtime,
};

#[cfg(test)]
mod crate_root_reexport_tests {
    use super::*;

    #[test]
    fn private_hnsw_root_exports_separate_client_and_server_helper_surfaces() {
        let _client_upload_validator: fn(
            &PrivateHnswOramUploadBundle,
        ) -> Result<Vec<String>, PrivateHnswClientError> = validate_private_hnsw_oram_upload_bundle;
        let _server_upload_validator: fn(
            &ServerPrivateHnswOramUploadBundle,
        ) -> Result<Vec<String>, PrivateHnswOramError> =
            validate_server_private_hnsw_oram_upload_bundle;

        let _client_writeback_budget: fn(&OramParams) -> Result<usize, PrivateHnswClientError> =
            private_hnsw_oram_fixed_writeback_bucket_budget;
        let _server_writeback_budget: fn(&OramParams) -> Result<usize, PrivateHnswOramError> =
            server_private_hnsw_oram_fixed_writeback_bucket_budget;

        let _server_commit_planner: fn(
            u64,
            u64,
            &str,
            &[String],
            &[PrivateHnswOramBucket],
        ) -> Result<
            ServerPrivateHnswOramCommitPlan,
            PrivateHnswOramError,
        > = plan_server_private_hnsw_oram_commit;
    }
}
